import type {
  CommissionRecord,
  ElectorRecord,
  FieldSessionRecord,
  SubVoteOperations,
} from "@/features/votes/model/vote-operations.types";

export function createVoteOperationsFixtures() {
  const subVotes: SubVoteOperations[] = [
    {
      id: "representative-election",
      voteId: "active-general",
      title: "대표 후보 선출",
      description: "운영위원회 대표 1인을 선출합니다.",
      type: "CANDIDATE",
      status: "OPEN",
      sortOrder: 0,
      policy: {
        privacyMode: "SECRET",
        participationUnit: "INDIVIDUAL",
        resultStorageMode: "DATABASE",
        voteWeightMode: "EQUAL",
      },
      candidates: [
        {
          id: "candidate-1",
          candidateNo: 1,
          name: "김대표",
          description: "투표 운영 자동화와 감사 추적 강화를 제안합니다.",
          status: "ACTIVE",
        },
        {
          id: "candidate-2",
          candidateNo: 2,
          name: "박운영",
          description: "선거인 지원 프로세스 개선을 제안합니다.",
          status: "ACTIVE",
        },
      ],
      turnout: {
        participationUnit: "INDIVIDUAL",
        voteWeightMode: "EQUAL",
        eligibleElectorCount: 3,
        eligibleVotingUnitCount: 3,
        participantCount: 2,
        participatedVotingUnitCount: 2,
        turnoutRate: 66.7,
        eligibleVoteWeight: 3,
        participatedVoteWeight: 2,
        weightedTurnoutRate: 66.7,
      },
      result: null,
    },
    {
      id: "budget-approval",
      voteId: "scheduled-budget",
      title: "예산안 승인",
      description: "제출된 예산안의 승인 여부를 결정합니다.",
      type: "YES_NO",
      status: "DRAFT",
      sortOrder: 0,
      policy: {
        privacyMode: "PUBLIC",
        participationUnit: "INDIVIDUAL",
        resultStorageMode: "DATABASE",
        voteWeightMode: "EQUAL",
      },
      candidates: [
        {
          id: "candidate-budget-1",
          candidateNo: 1,
          name: "찬성",
          description: "제출된 예산안을 승인합니다.",
          status: "ACTIVE",
        },
        {
          id: "candidate-budget-2",
          candidateNo: 2,
          name: "반대",
          description: "제출된 예산안을 반려합니다.",
          status: "ACTIVE",
        },
      ],
      turnout: null,
      result: null,
    },
    {
      id: "policy-revision",
      voteId: "completed-policy",
      title: "운영 규정 개정",
      description: "운영 규정 개정안의 채택 여부를 결정합니다.",
      type: "YES_NO",
      status: "CLOSED",
      sortOrder: 0,
      policy: {
        privacyMode: "SECRET",
        participationUnit: "INDIVIDUAL",
        resultStorageMode: "DATABASE",
        voteWeightMode: "EQUAL",
      },
      candidates: [
        {
          id: "candidate-policy-1",
          candidateNo: 1,
          name: "개정안 승인",
          description: "운영 규정 개정안을 승인합니다.",
          status: "ACTIVE",
        },
        {
          id: "candidate-policy-2",
          candidateNo: 2,
          name: "현행 유지",
          description: "기존 운영 규정을 유지합니다.",
          status: "ACTIVE",
        },
      ],
      turnout: {
        participationUnit: "INDIVIDUAL",
        voteWeightMode: "EQUAL",
        eligibleElectorCount: 7,
        eligibleVotingUnitCount: 7,
        participantCount: 6,
        participatedVotingUnitCount: 6,
        turnoutRate: 85.7,
        eligibleVoteWeight: 7,
        participatedVoteWeight: 6,
        weightedTurnoutRate: 85.7,
      },
      result: {
        privacyMode: "SECRET",
        participationUnit: "INDIVIDUAL",
        voteWeightMode: "EQUAL",
        participantCount: 6,
        participatedVoteWeight: 6,
        totalVoteCount: 6,
        totalWeightedVoteCount: 6,
        candidates: [
          {
            id: "candidate-policy-1",
            candidateNo: 1,
            name: "개정안 승인",
            description: "운영 규정 개정안을 승인합니다.",
            status: "ACTIVE",
            voteCount: 4,
            voteRate: 66.7,
            weightedVoteCount: 4,
            weightedVoteRate: 66.7,
          },
          {
            id: "candidate-policy-2",
            candidateNo: 2,
            name: "현행 유지",
            description: "기존 운영 규정을 유지합니다.",
            status: "ACTIVE",
            voteCount: 2,
            voteRate: 33.3,
            weightedVoteCount: 2,
            weightedVoteRate: 33.3,
          },
        ],
        votingChannels: [
          {
            channel: "ONLINE",
            participantCount: 5,
            participationRate: 83.3,
            participatedVoteWeight: 5,
            weightedParticipationRate: 83.3,
          },
          {
            channel: "ONSITE",
            participantCount: 1,
            participationRate: 16.7,
            participatedVoteWeight: 1,
            weightedParticipationRate: 16.7,
          },
        ],
      },
    },
  ];

  const electors: ElectorRecord[] = [
    {
      id: "elector-1",
      voteId: "active-general",
      name: "이선거",
      identifier: "member-101",
      phoneNumber: "010-****-1201",
      groupKey: "운영팀",
      voteWeight: 1,
      status: "ELIGIBLE",
      identityVerified: true,
    },
    {
      id: "elector-2",
      voteId: "active-general",
      name: "박미참",
      identifier: "member-102",
      phoneNumber: "010-****-3720",
      groupKey: "재무팀",
      voteWeight: 1,
      status: "ELIGIBLE",
      identityVerified: false,
    },
    {
      id: "elector-3",
      voteId: "active-general",
      name: "정참여",
      identifier: "member-103",
      phoneNumber: "010-****-9042",
      groupKey: "감사팀",
      voteWeight: 1,
      status: "ELIGIBLE",
      identityVerified: true,
    },
  ];

  const commissions: CommissionRecord[] = [
    {
      id: "commission-1",
      name: "전자투표 운영위원회",
      status: "ACTIVE",
      members: [
        {
          id: "commission-member-1",
          name: "김관리",
          role: "ADMIN",
          status: "ACTIVE",
        },
        {
          id: "commission-member-2",
          name: "오현장",
          role: "FIELD_MANAGER",
          status: "ACTIVE",
        },
      ],
    },
  ];

  const fieldSessions: FieldSessionRecord[] = [
    {
      id: "field-session-1",
      voteId: "active-general",
      commissionId: "commission-1",
      channel: "ONSITE",
      title: "본관 현장 투표소",
      locationName: "본관 1층 로비",
      address: "서울시 중구 운영로 12",
      managerIds: ["commission-member-2"],
      startsAt: "2026-08-18T00:00:00.000Z",
      endsAt: "2026-08-18T09:00:00.000Z",
      status: "OPEN",
    },
    {
      id: "field-session-2",
      voteId: "scheduled-budget",
      commissionId: "commission-1",
      channel: "VISIT",
      title: "지점 방문 투표",
      locationName: "서부 지점",
      address: "서울시 마포구 참여로 28",
      managerIds: ["commission-member-2"],
      startsAt: "2026-09-02T00:00:00.000Z",
      endsAt: "2026-09-02T06:00:00.000Z",
      status: "SCHEDULED",
    },
  ];

  return { commissions, electors, fieldSessions, subVotes };
}
